### ISSUE TITLE
Is this running in any production environments?

### ISSUE THREAD

**Issue by derekperkins** [benthor/clustersql#1]
This sounds great as I'm migrating from Google Cloud SQL to a self managed Percona XtraDB cluster.

**Comment by benthor** [comment]
Hi Derek,

I have deployed this without issue in at least one mariadb/galera production environment that I maintain. As the README states, this is just a very thin wrapper/multiplexer on the client-side. I recommend doing your own tests to determine if it suits your needs. If not, I recommend looking at something like [haproxy](http://haproxy.org) to do failover.

Cheers

**Comment by derekperkins** [comment]
@benthor It's working great for me and my cluster. It's just nice to know that someone, especially the maintainer, is using it in production and available in case any issues arise. We'll keep using it happily! Thanks!
